### ISSUE TITLE
menuitem Config crash

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#23]
Options / Settings-plugins / SyncEditing

```
Startup: total: 730ms, including plugins: 13ms
Python 3.6.5
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/user/.cudatext/py/cuda_sync_editing/__init__.py", line 49, in __init__
    parsed_config = json.load(open(fn_config))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 69 column 1 (char 2109)
```

**Comment by Alexey-T** [comment]
user.json не надо юзать- плагины обычно не юзают его. надо fn_config - "cuda_sync_editing.json",
а лучше даже .ini, так юзеру проще поправить.

**Comment by Alexey-T** [comment]
То есть так
надо юзать не json, а cudax_lib, в нем метод get_opt / set_opt, он понимает все коменты в json

get_opt имеет параметр- читать из user.json/ lexer config
