### ISSUE TITLE
crash in new tab opened with editing

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#50]
- активировали плаг
- правим слово
- вызвали новый таб CtrlN
-  в нем печатаем чтото (уже вижу статуc SyncEdit exited)
- переключились на исх таб

```
Startup: total: 910ms, including plugins: 15ms
Python 3.6.5
TreeHelpers: Markdown, PHP, Pascal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_sync_editing/__init__.py", line 269, in on_caret
    self.toggle()
  File "/home/user/.cudatext/py/cuda_sync_editing/__init__.py", line 97, in toggle
    for token in ed.get_token(TOKEN_LIST_SUB, self.start_l, self.end_l):
TypeError: 'NoneType' object is not iterable
Snippets found for lexers: HTML, HTML_, PHP, PHP_, Python, SCSS
```

**Comment by Alexey-T** [comment]
Может хочеш пометить таб что "в нем активен плаг"? посмотри апи set_prop(PROP_TAG)

**Comment by Alexey-T** [comment]
при активации плага пометим едитор - ed.set_prop(PROP_TAG, 'sync_edit:1' })

в on_NNN проверим что едитор с режимом
if ed_self.get_prop(PROP_TAG, 'sync_edit:0')=='1'
