### ISSUE TITLE
Python log error when activate edit mode on selected rows

### ISSUE THREAD

**Issue by iRamSoft** [viad00/cuda_sync_editing#51]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\CudaText\py\cuda_sync_editing\__init__.py", line 93, in toggle
    for token in ed.get_token(TOKEN_LIST_SUB, self.start_l, self.end_l):
NameError: name 'TOKEN_LIST_SUB' is not defined
```

**Comment by Alexey-T** [comment]
Так это Куд старый у тебя- обнови- на SF.net лежит бета 1.58
