### ISSUE TITLE
bug when editing to empty ID text

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#62]
правлю ИД. Делетом удалил весь ИД и печатаю новый ИД "s". плагин крешится. на скрине видно что марки сбились правее.

![screenshot from 2018-08-10 11-02-37](https://user-images.githubusercontent.com/4154978/43946107-f269458c-9c8c-11e8-9a21-a9e54cfaae54.png)

```
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_sync_editing/__init__.py", line 297, in on_caret
    self.redraw(ed_self)
  File "/home/user/.cudatext/py/cuda_sync_editing/__init__.py", line 318, in redraw
    new_key = self.pattern.match(first_y_line[start_pos:]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Alexey-T** [comment]
спасибо.
